/**
 * 英文词表（常见单词 / 名词 / 动词 / 形容词）
 *
 * 数据来源：西部数码域名查询客户端 Words.DomainWords()
 *   value  (545) -> {常见单词}
 *   value2 (999) -> {动词}
 *   value3 (974) -> {名词}
 *   value4 (991) -> {形容词}
 *
 * 口径为原样照搬：源码的词性划分较宽松（{动词} 里混有 abstract/account 这类
 * 名词兼类词），但既然目标是复刻其产出，这里不做词性重判，保持逐条一致。
 */

/**
 * {常见单词} —— 源码 value，545 条。
 *
 * 源码此表有两处特殊之处，转录时做了归一（属格式问题，非词条增删）：
 *   1. 大小写混排（USA / NewYork / WallStreet）—— 域名前缀必须小写，统一转小写；
 *   2. 尾部约 50 条是前面词条的小写重复（emoney/ebuy/monkey/istanbul…），
 *      小写化后与前文完全重合，由下方 unique() 去重。
 * 归一后实际参与组合的是去重后的词条，不影响产出集合本身。
 */
const COMMON_WORDS_RAW: string[] = [
  "sex", "business", "travel", "money", "music", "show", "usa", "news", "internet", "health",
  "web", "computer", "loans", "america", "china", "realestate", "car", "sports", "bank", "loan",
  "info", "free", "law", "my", "stocks", "insurance", "tv", "auto", "wireless", "biz",
  "casino", "domain", "email", "beauty", "finance", "stock", "japan", "game", "trade", "games",
  "buy", "europe", "home", "cars", "net", "mortgage", "shop", "software", "food", "tax",
  "shopping", "dvd", "newyork", "us", "medical", "jobs", "korea", "drugs", "art", "love",
  "movies", "movie", "auction", "hotel", "weather", "books", "canada", "search", "mail", "world",
  "online", "india", "porn", "golf", "asia", "homes", "pc", "medicine", "www", "xxx",
  "computers", "wallstreet", "football", "sales", "video", "fashion", "gambling", "california", "lawyer", "mexico",
  "market", "book", "sport", "lasvegas", "uk", "hot", "marketing", "hollywood", "film", "job",
  "mobile", "wine", "credit", "it", "holiday", "gold", "sell", "security", "australia", "design",
  "hongkong", "mp3", "com", "cool", "sale", "africa", "porno", "germany", "legal", "find",
  "help", "media", "cash", "drug", "b2b", "commerce", "network", "cinema", "go", "best",
  "ecommerce", "autos", "gay", "stockmarket", "ebusiness", "england", "college", "register", "brazil", "france",
  "phone", "thailand", "tickets", "ticket", "diet", "radio", "women", "doctor", "la", "banking",
  "broadband", "consulting", "entertainment", "fitness", "soccer", "creditcard", "baseball", "tennis", "jewelry", "technology",
  "advertising", "toys", "webdesign", "house", "employment", "losangeles", "chinese", "london", "domains", "hardware",
  "hawaii", "english", "florida", "flowers", "global", "hosting", "indonesia", "taiwan", "fishing", "financial",
  "adult", "the", "fun", "directory", "pharmacy", "girl", "italy", "investment", "basketball", "chat",
  "tech", "healthcare", "mutualfunds", "webhosting", "hotels", "tokyo", "tour", "kids", "live", "family",
  "city", "boy", "photo", "chicago", "american", "top", "cruise", "broker", "accounting", "pro",
  "girls", "lawyers", "toy", "texas", "information", "rent", "sexy", "education", "paris", "cancer",
  "digital", "engineering", "test", "baby", "bonds", "auctions", "lottery", "forsale", "woman", "god",
  "turkey", "christmas", "divorce", "ad", "club", "gifts", "delivery", "russia", "all", "wedding",
  "bio", "attorney", "hockey", "cd", "taxes", "vacation", "euro", "shipping", "argentina", "mall",
  "newzealand", "gas", "invest", "spain", "television", "restaurant", "construction", "university", "map", "press",
  "trading", "capital", "hk", "realty", "genome", "retirement", "singapore", "alaska", "coffee", "company",
  "drugstore", "oil", "furniture", "pets", "diamond", "biotech", "get", "islam", "bankruptcy", "3g",
  "pop", "antiques", "holidays", "gift", "cards", "career", "beer", "fly", "nyc", "life",
  "ski", "school", "washington", "pussy", "commercial", "casinos", "beautiful", "dogs", "dna", "people",
  "boston", "malaysia", "air", "cuba", "cooking", "your", "tourist", "play", "pizza", "office",
  "first", "diamonds", "water", "pda", "power", "madrid", "student", "new", "seattle", "big",
  "asian", "biotechnology", "bible", "audio", "hospital", "name", "electronics", "telecom", "istanbul", "men",
  "chile", "personal", "personalinjury", "airline", "theater", "miami", "investing", "nz", "energy", "international",
  "restaurants", "doctors", "more", "cosmetics", "cats", "cat", "wap", "3d", "general", "dot",
  "maps", "government", "flower", "switzerland", "consumer", "realtor", "apartment", "research", "ny", "photography",
  "israel", "host", "exchange", "cn", "management", "flight", "cellular", "models", "jazz", "model",
  "arizona", "traffic", "whois", "emoney", "dating", "atlanta", "ireland", "corporate", "ca", "abc",
  "seoul", "time", "hair", "lotto", "banks", "pet", "sanfrancisco", "download", "ebiz", "holland",
  "clubs", "vitamins", "virginia", "export", "express", "healthinsurance", "blackjack", "greece", "hobbies", "silver",
  "work", "unitedstates", "success", "dog", "erotic", "etrade", "man", "architecture", "domainnames", "boat",
  "massachusetts", "property", "smart", "trademark", "gaming", "gamble", "happy", "consultant", "arts", "creditcards",
  "cpa", "newspaper", "no", "apartments", "sound", "arab", "monkey", "webmaster", "cafe", "html",
  "in", "venture", "franchise", "lesbian", "financing", "fish", "houston", "vietnam", "style", "patent",
  "camera", "amsterdam", "bet", "networks", "stockbroker", "date", "wines", "cyber", "vacations", "finland",
  "isp", "kid", "party", "alabama", "trucks", "barcelona", "angel", "shoes", "space", "star",
  "start", "sun", "idaho", "egypt", "shanghai", "on", "politics", "account", "md", "med",
  "lease", "lebanon", "lifeinsurance", "iran", "jakarta", "ebuy", "homepage", "fax", "georgia", "astrology",
  "cruises", "yes", "airlines", "good", "land", "nutrition", "virtual", "camping", "master", "computing",
  "domainname", "discount", "multimedia", "psychology", "rome", "motorcycle", "orange", "data",
];

/** {常见单词} —— 小写归一并去重后的最终表 */
export const COMMON_WORDS: string[] = Array.from(new Set(COMMON_WORDS_RAW));

/** {动词} —— 源码 value2，999 条 */
export const VERBS: string[] = [
  "abstract", "abuse", "accept", "access", "account", "achieve", "act", "action", "add", "address",
  "advance", "advantage", "adventure", "advertise", "affect", "affiliate", "age", "agree", "aid", "aim",
  "air", "alert", "allow", "amount", "answer", "antique", "apparel", "appeal", "appear", "apply",
  "approach", "appropriate", "archive", "arm", "array", "article", "ask", "assist", "associate", "assume",
  "attack", "attempt", "attend", "auction", "audit", "author", "average", "avoid", "award", "baby",
  "back", "background", "bag", "balance", "ball", "band", "bank", "bar", "bargain", "base",
  "bath", "battle", "bay", "be", "beach", "bear", "beat", "become", "bed", "begin",
  "believe", "bell", "benefit", "best", "better", "bid", "bike", "bill", "bin", "bird",
  "birth", "black", "blank", "block", "blog", "blood", "blow", "blue", "board", "boat",
  "bob", "body", "bond", "book", "boot", "border", "bottom", "bound", "bowl", "box",
  "brain", "branch", "brand", "break", "breakfast", "breast", "bridge", "brief", "bring", "broadcast",
  "brown", "browse", "budget", "bug", "build", "bulk", "bulletin", "bus", "bush", "button",
  "buy", "cable", "calculate", "calendar", "call", "camp", "campaign", "can", "cancel", "cap",
  "card", "care", "career", "carry", "cart", "cartoon", "case", "cash", "cast", "castle",
  "cat", "catalog", "catalogue", "catch", "cause", "census", "center", "centre", "certificate", "chain",
  "chair", "chairman", "challenge", "chamber", "chance", "change", "channel", "char", "character", "charge",
  "chart", "charter", "chat", "check", "chip", "choose", "church", "circle", "circuit", "claim",
  "class", "clean", "clear", "click", "clip", "clock", "close", "club", "coach", "coast",
  "cock", "code", "color", "colour", "come", "comfort", "command", "comment", "commission", "compact",
  "company", "compare", "complete", "con", "concern", "concert", "concrete", "condition", "conduct", "confirm",
  "conflict", "connect", "consent", "consider", "contact", "contain", "content", "contest", "continue", "contract",
  "contrast", "contribute", "control", "cook", "cool", "copy", "copyright", "core", "corner", "correct",
  "cost", "cotton", "count", "counter", "couple", "course", "court", "cover", "cream", "create",
  "credit", "crew", "cross", "cruise", "culture", "cup", "cut", "cycle", "damage", "dance",
  "date", "deal", "debate", "decide", "default", "define", "delay", "delete", "deliver", "demand",
  "demo", "deposit", "describe", "design", "detail", "determine", "develop", "die", "diet", "direct",
  "discount", "discover", "discuss", "dish", "disk", "display", "distance", "district", "dj", "do",
  "doctor", "document", "dog", "don", "dot", "double", "doubt", "down", "download", "draft",
  "draw", "dream", "dress", "drink", "drive", "drop", "drug", "dry", "earn", "earth",
  "eat", "echo", "edge", "edit", "effect", "email", "empty", "enable", "encourage", "end",
  "engineer", "enhance", "enjoy", "enlarge", "ensure", "enter", "equal", "establish", "estimate", "even",
  "evidence", "exact", "except", "exchange", "exercise", "exist", "exit", "expand", "expect", "experience",
  "explain", "explore", "export", "express", "eye", "face", "factor", "fail", "fair", "fall",
  "fan", "fantasy", "farm", "fashion", "fast", "fat", "father", "fax", "fear", "feature",
  "fee", "feed", "feel", "felt", "field", "fight", "figure", "file", "fill", "film",
  "filter", "finance", "find", "fine", "finish", "fire", "firm", "fish", "fit", "fix",
  "flag", "flash", "flight", "floor", "flow", "flower", "fly", "focus", "follow", "foot",
  "force", "ford", "forecast", "forest", "forget", "form", "format", "fort", "forward", "found",
  "fox", "frame", "frank", "free", "french", "front", "fruit", "fuck", "fuel", "full",
  "function", "fund", "further", "gain", "game", "garden", "gas", "gear", "general", "generate",
  "get", "gift", "give", "glass", "go", "golf", "google", "grade", "graduate", "grant",
  "gray", "green", "grey", "ground", "group", "grow", "guarantee", "guard", "guess", "guide",
  "gun", "guy", "hand", "handle", "happen", "harry", "hat", "hate", "have", "head",
  "hear", "heat", "help", "hide", "hill", "hire", "hit", "hold", "hole", "holiday",
  "home", "hop", "hope", "horse", "host", "house", "humor", "husband", "ice", "identify",
  "image", "impact", "implement", "import", "improve", "inch", "include", "increase", "index", "indicate",
  "influence", "initial", "ink", "input", "insert", "install", "instance", "institute", "instrument", "interest",
  "interview", "inventory", "iron", "issue", "jack", "japan", "jazz", "job", "join", "joint",
  "journey", "judge", "jump", "keep", "key", "kid", "kill", "kit", "know", "label",
  "labor", "labour", "lack", "land", "landscape", "last", "launch", "layer", "lead", "league",
  "learn", "leather", "leave", "let", "letter", "level", "license", "light", "like", "limit",
  "line", "link", "list", "listen", "live", "load", "loan", "lock", "lodge", "log",
  "long", "look", "loop", "lord", "lose", "lot", "love", "low", "lower", "lunch",
  "machine", "mail", "maintain", "major", "make", "man", "manage", "map", "mar", "march",
  "mark", "market", "mass", "master", "match", "matter", "mature", "mean", "measure", "medicine",
  "meet", "mention", "merchandise", "mesh", "message", "metal", "meter", "middle", "milk", "mind",
  "mine", "minister", "mirror", "miss", "mix", "model", "modify", "monitor", "moon", "mortgage",
  "mother", "motion", "motor", "mount", "mouse", "mouth", "move", "muscle", "name", "narrow",
  "near", "need", "negative", "net", "network", "nick", "noise", "note", "notice", "notify",
  "number", "object", "obtain", "occur", "off", "offer", "officer", "oil", "open", "operate",
  "order", "out", "output", "own", "pack", "package", "page", "pain", "paint", "pair",
  "palm", "pan", "panel", "paper", "paragraph", "parallel", "parent", "park", "part", "participate",
  "partner", "party", "pass", "patch", "patent", "pattern", "pay", "peak", "pearl", "people",
  "perfect", "perform", "permit", "pet", "phase", "phone", "pick", "picture", "piece", "pilot",
  "pin", "pink", "place", "plain", "plan", "plant", "plate", "play", "please", "plot",
  "plug", "pocket", "point", "police", "poll", "pool", "pop", "port", "portion", "position",
  "post", "potter", "power", "practice", "premier", "prepare", "present", "press", "pressure", "prevent",
  "preview", "price", "prime", "print", "process", "produce", "profile", "profit", "program", "programme",
  "progress", "project", "promote", "proof", "protect", "provide", "provision", "pull", "pulse", "pump",
  "purchase", "purpose", "push", "put", "quarter", "queen", "query", "question", "quote", "race",
  "radio", "rain", "raise", "ram", "range", "rank", "rape", "rate", "ray", "reach",
  "read", "ready", "rear", "reason", "receive", "recommend", "record", "reduce", "refer", "reference",
  "reflect", "reform", "regard", "register", "release", "remain", "remember", "remove", "rent", "repair",
  "replace", "reply", "report", "represent", "request", "require", "research", "reserve", "resort", "respect",
  "respond", "rest", "result", "resume", "retail", "return", "reverse", "review", "rice", "ride",
  "right", "ring", "rise", "risk", "rock", "roll", "romance", "room", "root", "round",
  "route", "row", "rule", "run", "saint", "salt", "sample", "satellite", "save", "saw",
  "say", "scale", "scan", "schedule", "scheme", "school", "score", "screen", "script", "search",
  "season", "seat", "second", "section", "secure", "see", "seek", "seem", "select", "sell",
  "send", "sense", "separate", "sequence", "serve", "service", "set", "sex", "shape", "share",
  "sheet", "shell", "shift", "ship", "shirt", "shop", "short", "show", "shower", "side",
  "sign", "signal", "silver", "single", "sit", "site", "size", "ski", "skin", "skip",
  "sky", "sleep", "slide", "slot", "slow", "smart", "smooth", "snow", "soil", "sort",
  "sound", "source", "space", "spam", "speak", "specify", "speed", "spend", "spirit", "split",
  "sponsor", "sport", "spot", "spread", "spring", "spy", "square", "stable", "staff", "stage",
  "stand", "star", "start", "state", "station", "stay", "steel", "step", "stick", "still",
  "stock", "stone", "stop", "store", "storm", "stream", "stress", "strike", "string", "strip",
  "structure", "study", "stuff", "style", "sub", "subject", "submit", "subscribe", "suck", "sugar",
  "suggest", "suit", "sum", "summer", "sun", "supply", "support", "surface", "survey", "switch",
  "table", "tag", "take", "talk", "tank", "tape", "target", "task", "tax", "teach",
  "team", "telephone", "tell", "term", "test", "thank", "theme", "think", "thread", "ticket",
  "time", "tip", "title", "toll", "tool", "top", "total", "touch", "tour", "tower",
  "toy", "track", "trade", "trademark", "traffic", "trail", "train", "transfer", "transit", "transition",
  "transport", "travel", "treat", "tree", "trip", "trouble", "truck", "true", "trust", "try",
  "turn", "twin", "type", "understand", "up", "update", "upgrade", "upload", "use", "vacation",
  "value", "vary", "view", "visa", "visit", "voice", "void", "volunteer", "vote", "wait",
  "walk", "wall", "wallpaper", "want", "war", "warm", "waste", "watch", "water", "wave",
  "wear", "weather", "web", "wed", "weekend", "weight", "welcome", "well", "wet", "wheel",
  "white", "wholesale", "will", "win", "wind", "wine", "winter", "wire", "wish", "wonder",
  "word", "work", "wow", "write", "wrong", "yellow", "zero", "zip", "zone",
];

/** {名词} —— 源码 value3，974 条 */
export const NOUNS: string[] = [
  "above", "access", "accommodation", "account", "act", "action", "active", "activity", "ad", "add",
  "addition", "address", "administration", "adult", "advertising", "advice", "africa", "age", "agency", "agent",
  "agreement", "air", "airport", "al", "album", "am", "amazon", "america", "american", "amount",
  "an", "analysis", "animal", "annual", "answer", "anti", "application", "approach", "apr", "april",
  "archive", "archives", "are", "area", "art", "article", "artist", "arts", "as", "asian",
  "ass", "assessment", "association", "at", "audio", "aug", "august", "australia", "author", "authority",
  "auto", "availability", "average", "award", "baby", "back", "bad", "band", "bank", "bar",
  "base", "basic", "basis", "bay", "be", "beach", "beauty", "bed", "being", "best",
  "better", "bid", "bill", "bin", "bit", "black", "blog", "blood", "blue", "board",
  "body", "book", "box", "boy", "brand", "british", "brown", "browse", "browser", "budget",
  "build", "building", "bush", "business", "button", "buy", "ca", "cable", "calendar", "california",
  "call", "camera", "can", "canada", "cancer", "capital", "car", "card", "cards", "care",
  "career", "carolina", "cart", "case", "cash", "casino", "catalog", "category", "cause", "cd",
  "cell", "center", "central", "centre", "change", "channel", "chapter", "chat", "check", "chicago",
  "child", "china", "choice", "christian", "christmas", "church", "city", "class", "classic", "clear",
  "click", "client", "close", "clothing", "club", "co", "code", "collection", "college", "color",
  "come", "coming", "command", "comment", "commercial", "commission", "committee", "common", "communication", "communications",
  "community", "company", "compare", "computer", "condition", "conditions", "conference", "connection", "construction", "consumer",
  "contact", "content", "contents", "contract", "control", "copy", "copyright", "corporation", "cost", "costs",
  "council", "country", "county", "course", "court", "cover", "credit", "cross", "culture", "current",
  "custom", "customer", "cut", "daily", "data", "database", "date", "david", "day", "days",
  "dc", "de", "deal", "death", "dec", "december", "decision", "degree", "delivery", "department",
  "description", "design", "details", "development", "director", "directory", "discount", "discussion", "disease", "display",
  "distance", "distribution", "district", "division", "do", "document", "dog", "domain", "double", "down",
  "drive", "drug", "due", "dvd", "earth", "east", "edition", "editor", "education", "effect",
  "effects", "el", "electronics", "email", "employment", "en", "end", "energy", "engine", "engineering",
  "england", "english", "enough", "entertainment", "entry", "environment", "equipment", "error", "est", "estate",
  "europe", "european", "even", "event", "evidence", "example", "exchange", "executive", "experience", "express",
  "extra", "face", "fact", "fall", "family", "faq", "far", "fast", "favorite", "fax",
  "feature", "feb", "february", "federal", "feed", "feedback", "feel", "female", "few", "field",
  "figure", "file", "film", "final", "finance", "find", "fine", "fire", "first", "five",
  "flash", "florida", "focus", "following", "food", "force", "form", "format", "forum", "forward",
  "found", "foundation", "four", "france", "free", "french", "fri", "friday", "friend", "friendly",
  "front", "full", "fun", "function", "fund", "furniture", "future", "gallery", "game", "garden",
  "gas", "gay", "general", "george", "germany", "get", "getting", "gift", "girl", "give",
  "given", "glass", "gmt", "go", "god", "going", "gold", "golf", "good", "google",
  "government", "great", "green", "ground", "group", "growth", "guide", "hair", "half", "hall",
  "hand", "hardware", "have", "he", "head", "health", "heart", "help", "here", "hi",
  "high", "hill", "history", "hold", "holiday", "home", "homepage", "hope", "horse", "hospital",
  "hotel", "hour", "hours", "house", "housing", "hp", "html", "human", "id", "idea",
  "ie", "ii", "iii", "image", "impact", "in", "inc", "income", "increase", "independent",
  "index", "india", "individual", "industry", "info", "information", "inn", "input", "inside", "institute",
  "insurance", "interest", "interface", "international", "internet", "introduction", "investment", "ip", "island", "issue",
  "it", "italy", "item", "james", "jan", "january", "japan", "jewelry", "job", "john",
  "join", "journal", "july", "june", "keep", "key", "kind", "king", "kingdom", "kit",
  "kitchen", "know", "knowledge", "la", "lake", "land", "language", "large", "last", "latest",
  "law", "lead", "learning", "least", "leave", "left", "length", "lesbian", "let", "letter",
  "level", "library", "license", "life", "light", "like", "limited", "line", "link", "links",
  "linux", "list", "listing", "little", "living", "loan", "local", "location", "log", "logo",
  "london", "look", "looking", "loss", "lost", "lot", "love", "low", "lower", "ma",
  "mac", "machine", "magazine", "mail", "main", "major", "make", "making", "male", "man",
  "management", "manager", "manufacturer", "map", "mar", "march", "mark", "market", "marketing", "master",
  "material", "matter", "max", "maximum", "may", "me", "mean", "means", "medical", "medicine",
  "meet", "meeting", "member", "memory", "men", "menu", "message", "method", "mexico", "michael",
  "middle", "might", "military", "million", "mind", "minutes", "mobile", "mode", "model", "mon",
  "monday", "money", "month", "more", "mortgage", "mother", "move", "movie", "ms", "much",
  "multiple", "music", "must", "name", "names", "national", "natural", "nature", "navigation", "necessary",
  "need", "net", "network", "news", "newsletter", "nice", "night", "no", "none", "north",
  "note", "nothing", "notice", "nov", "november", "now", "nude", "number", "numbers", "ny",
  "object", "oct", "october", "offer", "office", "official", "oh", "oil", "ok", "old",
  "one", "open", "operation", "operations", "opportunity", "option", "or", "order", "organization", "original",
  "out", "outside", "over", "overall", "overview", "owner", "pa", "package", "page", "paper",
  "park", "part", "particular", "parts", "party", "password", "past", "paul", "pay", "payment",
  "pc", "people", "percent", "perfect", "performance", "period", "person", "personal", "peter", "phone",
  "photo", "picture", "place", "plan", "planning", "play", "player", "plus", "pm", "point",
  "poker", "police", "policy", "population", "porn", "port", "position", "possible", "post", "potential",
  "power", "practice", "present", "president", "press", "price", "primary", "print", "printer", "prior",
  "privacy", "private", "pro", "problem", "process", "product", "production", "professional", "profile", "program",
  "programme", "project", "property", "protection", "public", "publisher", "purchase", "purpose", "pussy", "put",
  "quality", "question", "quick", "quote", "radio", "range", "rate", "rates", "rating", "re",
  "read", "reading", "ready", "real", "reason", "recent", "record", "red", "reference", "region",
  "register", "registration", "regular", "release", "rental", "reply", "report", "request", "research", "resource",
  "response", "result", "retail", "return", "review", "right", "risk", "river", "road", "robert",
  "rock", "role", "room", "rooms", "round", "rule", "run", "running", "safe", "safety",
  "sale", "sales", "same", "sample", "sat", "saturday", "save", "say", "schedule", "school",
  "science", "score", "screen", "sea", "search", "season", "second", "section", "security", "see",
  "selection", "self", "sell", "seller", "sellers", "sent", "sep", "september", "series", "server",
  "service", "services", "set", "sex", "share", "ship", "shipping", "shoes", "shop", "shopping",
  "short", "show", "side", "sign", "silver", "simple", "single", "site", "six", "size",
  "small", "smith", "so", "social", "society", "software", "solution", "someone", "son", "song",
  "sort", "sound", "source", "south", "space", "special", "specific", "speed", "sport", "spring",
  "staff", "standard", "star", "start", "starting", "state", "statement", "station", "statistics", "status",
  "stay", "step", "still", "stock", "stop", "storage", "store", "story", "strategy", "street",
  "structure", "student", "study", "stuff", "style", "subject", "success", "summary", "summer", "sun",
  "sunday", "super", "supply", "support", "survey", "system", "table", "take", "taking", "talk",
  "tax", "team", "tech", "technical", "technology", "teen", "teens", "telephone", "tell", "term",
  "terms", "test", "texas", "text", "thanks", "then", "there", "thing", "things", "think",
  "third", "thomas", "thought", "thread", "three", "thursday", "thus", "time", "times", "title",
  "today", "tool", "top", "topic", "total", "tour", "town", "track", "trade", "traffic",
  "training", "transfer", "travel", "treatment", "tree", "true", "try", "tuesday", "turn", "tv",
  "two", "tx", "type", "uk", "union", "unit", "university", "update", "url", "us",
  "usa", "use", "user", "using", "valley", "value", "values", "version", "video", "view",
  "virginia", "visit", "voice", "volume", "vote", "wall", "want", "war", "warning", "washington",
  "watch", "water", "way", "ways", "weather", "web", "website", "wed", "wedding", "wednesday",
  "week", "weight", "welcome", "well", "west", "western", "while", "white", "who", "whole",
  "why", "will", "win", "window", "windows", "wine", "wireless", "wish", "woman", "word",
  "words", "work", "working", "works", "world", "writing", "yahoo", "year", "years", "yellow",
  "yes", "york", "young", "zip",
];

/** {形容词} —— 源码 value4，991 条 */
export const ADJECTIVES: string[] = [
  "able", "about", "above", "absolute", "abstract", "academic", "accepted", "accessible", "accessory", "according",
  "accurate", "acid", "acting", "active", "actual", "additional", "addressed", "administrative", "adopted", "adult",
  "advance", "advanced", "advisory", "affected", "affordable", "african", "after", "aged", "ago", "agreed",
  "agricultural", "ahead", "alert", "alive", "all", "alone", "alpha", "alternative", "amateur", "amazing",
  "amended", "american", "anal", "ancient", "animal", "announced", "annual", "anonymous", "another", "anti",
  "antique", "any", "apart", "applicable", "applied", "appointed", "appropriate", "approved", "asian", "assigned",
  "assistant", "associate", "atlantic", "attached", "august", "australian", "authorized", "automatic", "automotive", "available",
  "average", "aware", "away", "awesome", "back", "bad", "banner", "base", "based", "basic",
  "bass", "bay", "beat", "beautiful", "becoming", "beginning", "behind", "best", "beta", "better",
  "betting", "big", "billion", "binding", "biological", "black", "blank", "blind", "blonde", "blue",
  "bold", "bone", "born", "both", "bottom", "bound", "brief", "bright", "british", "broad",
  "broadband", "broken", "brown", "built", "burning", "bush", "busty", "busy", "calculated", "camp",
  "canadian", "capable", "capital", "catholic", "cc", "cd", "cellular", "center", "central", "certain",
  "certified", "chance", "changed", "changing", "charged", "cheap", "checked", "chemical", "chicken", "chief",
  "chinese", "choice", "christian", "civil", "classic", "classical", "classified", "clean", "clear", "clinical",
  "close", "closed", "closing", "cold", "collect", "collected", "color", "colour", "combined", "comfortable",
  "comic", "coming", "commercial", "committed", "common", "compact", "compatible", "competitive", "complete", "completed",
  "complex", "comprehensive", "concerned", "concrete", "confirmed", "connected", "considered", "consistent", "constant", "contained",
  "contemporary", "content", "continued", "continuing", "continuous", "controlled", "converted", "cool", "corporate", "correct",
  "corresponding", "counter", "covered", "crack", "crazy", "creative", "criminal", "critical", "cross", "cultural",
  "current", "custom", "cut", "cute", "cutting", "czech", "daily", "dangerous", "dark", "dead",
  "dear", "decided", "dedicated", "deep", "defined", "deluxe", "democratic", "dental", "dependent", "derived",
  "described", "designed", "desired", "detailed", "determined", "developed", "developing", "different", "difficult", "digital",
  "direct", "directed", "dirty", "disabled", "discovered", "distributed", "domestic", "done", "double", "down",
  "downtown", "dress", "driven", "driving", "dry", "dual", "due", "dutch", "dynamic", "each",
  "earlier", "early", "east", "eastern", "easy", "economic", "edited", "editorial", "educational", "effective",
  "efficient", "eight", "elected", "electric", "electrical", "electronic", "elementary", "eligible", "employed", "empty",
  "ended", "english", "enhanced", "enough", "entire", "entitled", "environmental", "equal", "equivalent", "erotic",
  "essential", "established", "ethnic", "european", "even", "every", "everyday", "evil", "ex", "exact",
  "excellent", "excess", "exciting", "exclusive", "executive", "existing", "expected", "expensive", "experienced", "experimental",
  "expert", "express", "expressed", "extended", "extensive", "external", "extra", "extreme", "fair", "false",
  "familiar", "famous", "fantastic", "far", "fast", "fat", "favorite", "favourite", "featured", "federal",
  "female", "few", "fifth", "fighting", "filled", "final", "financial", "fine", "finished", "firm",
  "first", "fiscal", "fit", "five", "fixed", "flash", "flat", "flexible", "fly", "flying",
  "focused", "following", "forced", "foreign", "formal", "formed", "former", "forward", "foster", "found",
  "four", "fourth", "frank", "free", "french", "fresh", "friendly", "front", "fucking", "full",
  "functional", "fundamental", "funny", "further", "future", "game", "gay", "general", "generic", "genetic",
  "german", "giant", "given", "giving", "global", "go", "going", "gold", "golden", "gone",
  "good", "graduate", "grand", "granted", "graphic", "gratis", "gray", "great", "greater", "greatest",
  "greek", "green", "grey", "gross", "growing", "hairy", "half", "happy", "hard", "hardcore",
  "hardcover", "healthy", "heard", "hearing", "heavy", "held", "helpful", "here", "hidden", "high",
  "higher", "hip", "historic", "historical", "hollywood", "holy", "home", "hot", "huge", "human",
  "hundred", "ideal", "identified", "ii", "iii", "il", "ill", "illegal", "immediate", "implemented",
  "important", "impossible", "improved", "improving", "in", "included", "incorporated", "increased", "increasing", "independent",
  "indian", "individual", "industrial", "informed", "initial", "initiative", "inner", "innovative", "inside", "instant",
  "integrated", "intellectual", "intended", "interactive", "interested", "interesting", "interior", "internal", "international", "interracial",
  "involved", "irish", "iron", "italian", "iv", "japanese", "jet", "jewish", "joined", "joint",
  "junior", "just", "kept", "key", "kind", "known", "large", "larger", "last", "late",
  "later", "latest", "latin", "lay", "leading", "learned", "least", "lee", "left", "legal",
  "legislative", "lesbian", "less", "level", "li", "liberal", "licensed", "light", "like", "likely",
  "limited", "linear", "linked", "liquid", "listed", "little", "live", "living", "local", "located",
  "long", "looking", "lost", "loved", "low", "lowest", "mad", "made", "magic", "magnetic",
  "main", "maintained", "major", "male", "manual", "many", "marine", "marked", "married", "mass",
  "massive", "master", "matching", "material", "matt", "mature", "maximum", "mean", "meaning", "measured",
  "mechanical", "medical", "medium", "meet", "mental", "metal", "mexican", "micro", "mid", "middle",
  "military", "million", "mini", "minimum", "minor", "minute", "miscellaneous", "missed", "missing", "mixed",
  "mobile", "model", "modern", "modified", "molecular", "monthly", "more", "most", "motor", "moved",
  "moving", "much", "multiple", "municipal", "musical", "must", "mutual", "naked", "narrow", "national",
  "nationwide", "native", "natural", "near", "nearby", "necessary", "needed", "negative", "neither", "net",
  "new", "next", "nice", "nine", "no", "none", "normal", "north", "northern", "northwest",
  "noted", "novel", "nuclear", "nude", "null", "numerous", "objective", "observed", "obvious", "off",
  "official", "ok", "okay", "old", "older", "on", "one", "ongoing", "online", "only",
  "open", "opened", "opening", "operating", "operational", "optical", "optional", "oral", "orange", "ordered",
  "organic", "organized", "oriented", "original", "other", "otherwise", "out", "outdoor", "outside", "outstanding",
  "over", "overall", "own", "owned", "pacific", "paid", "paperback", "parallel", "participating", "particular",
  "pass", "passing", "past", "patent", "patient", "paying", "perfect", "permanent", "personal", "pet",
  "physical", "piano", "pink", "placed", "plain", "plane", "planned", "plastic", "played", "plus",
  "political", "poor", "pop", "popular", "port", "portable", "positive", "possible", "postal", "posted",
  "potential", "powered", "powerful", "practical", "preferred", "pregnant", "premier", "premium", "prepared", "prescription",
  "present", "pretty", "previous", "primary", "prime", "principal", "printable", "prior", "private", "prize",
  "pro", "professional", "progressive", "prohibited", "proof", "proper", "protected", "proud", "public", "published",
  "pure", "purple", "pursuant", "pussy", "qualified", "quality", "quick", "quiet", "radio", "raised",
  "random", "rank", "rapid", "rare", "raw", "ready", "real", "rear", "reasonable", "received",
  "recent", "recognized", "recorded", "red", "reduced", "regional", "registered", "regular", "regulation", "regulatory",
  "related", "relative", "relevant", "reliable", "religious", "remaining", "remote", "removed", "rental", "reported",
  "representative", "represented", "requested", "required", "reserved", "resident", "residential", "respective", "responsible", "reverse",
  "revised", "rich", "right", "roman", "romance", "rose", "round", "royal", "rubber", "running",
  "rural", "russian", "safe", "said", "salt", "same", "satellite", "saved", "saving", "scheduled",
  "scientific", "scottish", "searching", "sec", "second", "secondary", "secret", "secure", "seeing", "select",
  "selected", "self", "senior", "sensitive", "sent", "separate", "serial", "serious", "set", "seven",
  "several", "severe", "sexual", "sexy", "shared", "sharing", "sharp", "shaved", "short", "shot",
  "sick", "side", "sign", "signal", "signed", "significant", "silver", "similar", "simple", "single",
  "sitting", "six", "size", "slow", "small", "smaller", "smart", "smoking", "smooth", "social",
  "soft", "solar", "sold", "solid", "some", "sorry", "sorted", "sound", "south", "southern",
  "spanish", "speaking", "special", "specific", "specified", "spent", "spiritual", "split", "sporting", "spread",
  "square", "stable", "stainless", "standard", "standing", "star", "starting", "stated", "static", "statistical",
  "stereo", "sterling", "still", "stock", "stone", "straight", "strange", "strategic", "strong", "structural",
  "subject", "substantial", "successful", "such", "sufficient", "suitable", "summary", "super", "superior", "supported",
  "supporting", "supreme", "sure", "surface", "surrounding", "sustainable", "sweet", "swimming", "swiss", "taken",
  "taking", "technical", "teen", "temporary", "ten", "terminal", "tested", "then", "thin", "thinking",
  "third", "thousand", "three", "through", "tight", "tiny", "together", "top", "total", "traditional",
  "treated", "tried", "tropical", "true", "trying", "turned", "tutorial", "twenty", "twin", "two",
  "typical", "ultimate", "ultra", "unable", "under", "underground", "understanding", "union", "unique", "united",
  "universal", "unknown", "unlimited", "up", "upcoming", "upper", "urban", "used", "useful", "usual",
  "utility", "valid", "valuable", "variable", "various", "vertical", "very", "vi", "virgin", "virtual",
  "visible", "visual", "void", "volunteer", "waiting", "walking", "wanted", "warm", "warning", "waste",
  "weather", "wed", "weekly", "welcome", "well", "west", "western", "wet", "whatever", "white",
  "whole", "wholesale", "wide", "wild", "willing", "winning", "wireless", "won", "wonderful", "working",
  "world", "worldwide", "worse", "worst", "worth", "written", "wrong", "xxx", "yellow", "young",
  "zero",
];
