/**
 * 城市 / 省份 / 区号 地理数据
 *
 * 数据来源：西部数码域名查询客户端 Words.DomainWords()
 *   value6  (333) -> {区号}
 *   value7  (419) -> {城市}
 *   value12 (880) -> {城市简写}
 *   value13 (30)  -> {省份简写}
 *
 * 口径为「照搬源码 + 修正明确缺陷」：取值一律照搬，仅对 value12 做去重
 * （原表 880 条里 tl/wc/hz 等大量重复，重复项在笛卡尔积中不产生新组合，
 * 只会让组合数预估虚高，属实缺陷）。
 */

/** {区号} —— 源码 value6，333 条全国电话区号 */
export const AREA_CODES: string[] = [
  "010", "020", "021", "022", "023", "024", "025", "027", "028", "029",
  "0310", "0311", "0312", "0313", "0314", "0315", "0316", "0317", "0318", "0319",
  "0335", "0349", "0350", "0351", "0352", "0353", "0354", "0355", "0356", "0357",
  "0358", "0359", "0370", "0371", "0372", "0373", "0374", "0375", "0376", "0377",
  "0378", "0379", "0391", "0392", "0393", "0394", "0395", "0396", "0398", "0410",
  "0411", "0412", "0413", "0414", "0415", "0416", "0417", "0418", "0419", "0421",
  "0427", "0429", "0431", "0432", "0433", "0434", "0435", "0436", "0437", "0438",
  "0439", "0440", "0448", "0451", "0452", "0453", "0454", "0455", "0456", "0457",
  "0458", "0459", "0464", "0467", "0468", "0469", "0470", "0471", "0472", "0473",
  "0474", "0475", "0476", "0477", "0478", "0479", "0482", "0483", "0510", "0511",
  "0512", "0513", "0514", "0515", "0516", "0517", "0518", "0519", "0523", "0527",
  "0530", "0531", "0532", "0533", "0534", "0535", "0536", "0537", "0538", "0539",
  "0543", "0546", "0550", "0551", "0552", "0553", "0554", "0555", "0556", "0557",
  "0558", "0559", "0561", "0562", "0563", "0564", "0565", "0566", "0570", "0571",
  "0572", "0573", "0574", "0575", "0576", "0577", "0578", "0579", "0580", "0591",
  "0592", "0593", "0594", "0595", "0596", "0597", "0598", "0599", "0631", "0632",
  "0633", "0634", "0635", "0660", "0662", "0663", "0668", "0691", "0692", "0701",
  "0710", "0711", "0712", "0713", "0714", "0715", "0716", "0717", "0718", "0719",
  "0722", "0724", "0728", "0730", "0731", "0732", "0733", "0734", "0735", "0736",
  "0737", "0738", "0739", "0743", "0744", "0745", "0746", "0750", "0751", "0752",
  "0753", "0754", "0755", "0756", "0757", "0758", "0759", "0760", "0762", "0763",
  "0766", "0768", "0769", "0770", "0771", "0772", "0773", "0774", "0775", "0776",
  "0777", "0778", "0779", "0790", "0791", "0792", "0793", "0794", "0795", "0796",
  "0797", "0798", "0799", "0812", "0813", "0816", "0817", "0818", "0825", "0826",
  "0827", "0830", "0831", "0832", "0833", "0834", "0835", "0836", "0837", "0838",
  "0839", "0851", "0852", "0853", "0854", "0855", "0856", "0857", "0858", "0859",
  "0870", "0871", "0872", "0873", "0874", "0875", "0876", "0877", "0878", "0879",
  "0883", "0886", "0887", "0888", "0891", "0892", "0893", "0894", "0895", "0896",
  "0897", "0898", "0901", "0902", "0903", "0906", "0908", "0909", "0910", "0911",
  "0912", "0913", "0914", "0915", "0916", "0917", "0919", "0930", "0931", "0932",
  "0933", "0934", "0935", "0936", "0937", "0938", "0939", "0941", "0943", "0951",
  "0952", "0953", "0954", "0955", "0970", "0971", "0972", "0973", "0974", "0975",
  "0976", "0977", "0979", "0990", "0991", "0992", "0993", "0994", "0995", "0996",
  "0997", "0998", "0999",
];

/** {城市} —— 源码 value7，419 条城市全拼 */
const CITY_PINYIN_RAW: string[] = [
  "beijing", "shanghai", "tianjin", "chongqing", "shijiazhuang", "nangong", "xinji", "hengshui", "xingtai", "shahe",
  "handan", "cangzhou", "botou", "renqiu", "tangshan", "qinhuangdao", "baoding", "chengde", "dingzhou", "zhuozhou",
  "langfang", "zhangjiakou", "taiyuan", "yuci", "xinzhou", "datong", "linfen", "houma", "yuncheng", "yangquan",
  "changzhi", "jincheng", "huhehaote", "jining", "erlianhaote", "baotou", "linhe", "wuhai", "dongsheng", "hailaer",
  "manzhouli", "yakeshi", "chifeng", "xilinhaote", "wulanhaote", "tongliao", "huolinguole", "zhalantun", "shenyang", "liaoyang",
  "tieling", "tiefa", "fushun", "anshan", "haicheng", "yingkou", "dalian", "wafangdian", "benxi", "dandong",
  "jinzhou", "jinxi", "xingcheng", "chaoyang", "beipiao", "fuxin", "panjin", "changhai", "changchun", "fuyu",
  "jilin", "huadian", "yanji", "tumen", "longjing", "dunhua", "tonghua", "jian", "hunjiang", "meihekou",
  "siping", "baicheng", "liaoyuan", "gongzhuling", "taonan", "baishan", "haerbin", "acheng", "zhaodong", "suihua",
  "yichun", "jiamusi", "hegang", "qitaihe", "shuangyashan", "tongjiang", "mudanjiang", "suifenhe", "jixi", "qiqihaer",
  "daqing", "beian", "heihe", "wudalianchi", "nanjing", "yizheng", "zhenjiang", "danyang", "changzhou", "wuxi",
  "yixing", "jiangyin", "suzhou", "changshu", "xuzhou", "lianyungang", "huaiyin", "huaian", "suqian", "yancheng",
  "dongtai", "yangzhou", "taizhou", "xinghua", "nantong", "wujiang", "hangzhou", "xiaoshan", "shaoxing", "huzhou",
  "jiaxing", "haining", "ningbo", "yuyao", "zhoushan", "taizhou", "linhai", "jiaojiang", "jinhua", "lanxi",
  "lishui", "quzhou", "jiangshan", "wenzhou", "yiwu", "dongyang", "ruian", "hefei", "huainan", "bangbu",
  "suzhou", "huaibei", "fuyang", "bozhou", "liuan", "chaohu", "chuzhou", "wuhu", "xuancheng", "huangshan",
  "maanshan", "tongling", "huangshan", "anqing", "taihu", "fuzhou", "putian", "nanping", "shaowu", "xiamen",
  "quanzhou", "shishi", "zhangzhou", "longyan", "sanming", "yongan", "ningde", "nanchang", "jiujiang", "jingdezhen",
  "shangrao", "yingtan", "yichun", "xinyu", "pingxiang", "ganzhou", "jian", "jinggangshan", "fuzhou", "lichuan",
  "lushan", "jinan", "liaocheng", "linqing", "dezhou", "zibo", "binzhou", "dongying", "weifang", "zhucheng",
  "qingzhou", "yantai", "weihai", "qingdao", "taian", "laiwu", "xintai", "jining", "qufu", "heze",
  "linyi", "rizhao", "zaozhuang", "tengzhou", "wendeng", "zhengzhou", "xinxiang", "jiaozuo", "anyang", "hebi",
  "puyang", "xuchang", "leihe", "zhumadian", "xinyang", "zhoukou", "pingdingshan", "luoyang", "sanmenxia", "yima",
  "nanyang", "kaifeng", "shangqiu", "wuhan", "macheng", "tianmen", "xiaogan", "yingcheng", "anlu", "xiantao",
  "jianghan", "jingsha", "honghu", "jingmen", "shishou", "ezhou", "huangshi", "xianning", "wuxue", "puqi",
  "xiangfan", "laohekou", "suizhou", "shiyan", "danjiangkou", "zhicheng", "yichang", "lichuan", "enshi", "changsha",
  "xiangtan", "xiangxiang", "zhuzhou", "yiyang", "yueyang", "changde", "jishou", "zhangjiajie", "loudi", "lianyuan",
  "lengshuijiang", "huaihua", "hongjiang", "hengyang", "leiyang", "shaoyang", "chenzhou", "yongzhou", "lengshuitan", "xiangxi",
  "guangzhou", "qingyuan", "dongwan", "shaoguan", "meizhou", "shantou", "chaozhou", "huizhou", "shanwei", "heyuan",
  "shenzhen", "zhanjiang", "maoming", "zhaoqing", "foshan", "zhongshan", "jiangmen", "yangjiang", "nanning", "pingxiang",
  "baise", "qinzhou", "beihai", "yulin", "guilin", "wuzhou", "liuzhou", "heshan", "hechi", "qinzhou",
  "haikou", "sanya", "tongshi", "danzhou", "chengdu", "maerkang", "xichang", "leshan", "deyang", "panzhihua",
  "yaan", "mianyang", "suining", "guangyuan", "nanchong", "daxian", "neijiang", "huaying", "yibin", "zigong",
  "luzhou", "guiyang", "liupanshui", "tongren", "kaili", "duyun", "anshun", "xingyi", "zunyi", "chishui",
  "bijie", "lasa", "rikaze", "shannan", "linzhi", "changdu", "naqu", "ali", "kunming", "dongchuan",
  "qujing", "zhaotong", "kaiyuan", "gejiu", "dali", "chuxiong", "baoshan", "yuxi", "wenshan", "simao",
  "jinghong", "luxi", "zhongdian", "liuku", "lincang", "lijiang", "xian", "xianyang", "yanan", "weinan",
  "yulin", "ankang", "shangzhou", "baoji", "hanzhong", "tongchuan", "lanzhou", "baiyin", "linxia", "wuwei",
  "zhangye", "jiuquan", "jiayuguan", "yumen", "jinchang", "tianshui", "pingliang", "xifeng", "xining", "haidong",
  "tongren", "gonghe", "maqin", "yushu", "delingha", "menyuan", "geermu", "haiyan", "yinchuan", "shizuishan",
  "qingtongxia", "wuzhong", "guyuan", "wulumuqi", "changji", "shihezi", "kuitun", "bole", "kelamayi", "tacheng",
  "yining", "aletai", "tulufan", "hami", "kuerle", "akesu", "kashi", "atushi", "hetian",
];

/**
 * {城市简写} —— 源码 value12，880 条。
 * 原表按城市顺序逐条手写，同名简写大量重复（tl 出现 3 次、wc 出现 6 次等）。
 * 重复项在笛卡尔积里不会产生新组合，只会让组合数预估虚高，因此去重。
 */
const CITY_ABBR_RAW: string[] = [
  "bj", "zq", "sh", "tj", "cc", "cs", "cz", "cd", "dl", "fs",
  "fz", "gz", "gy", "heb", "hk", "hd", "hz", "hf", "hz", "jz",
  "jx", "jl", "jn", "km", "lz", "lz", "ly", "nc", "nj", "nn",
  "nt", "nb", "qd", "qz", "sy", "sjz", "sz", "tz", "ts", "wf",
  "wh", "wh", "wx", "xm", "xa", "xc", "xz", "yz", "yt", "zz",
  "zz", "zs", "zh", "ab", "aks", "alsm", "alt", "al", "ak", "aq",
  "as", "as", "ay", "bc", "bs", "bs", "by", "bb", "bd", "bj",
  "bs", "bt", "byne", "bygl", "bz", "bh", "bx", "bj", "bz", "betl",
  "cz", "cd", "cd", "cj", "cz", "ch", "cy", "cz", "cd", "cz",
  "cf", "cz", "cz", "cx", "cz", "dl", "dd", "dq", "dt", "dxal",
  "dz", "dh", "dy", "dz", "dx", "dq", "dy", "eeds", "es", "ez",
  "fcg", "fs", "fx", "fy", "fz", "gn", "gz", "gz", "ga", "gy",
  "gg", "gl", "gl", "gy", "hb", "hd", "hn", "hx", "hm", "hz",
  "hb", "hc", "hg", "hh", "hs", "hy", "htd", "hy", "hz", "hz",
  "hh", "ha", "hb", "hh", "hn", "hg", "hn", "hs", "hs", "hhht",
  "hld", "hlbe", "hz", "jms", "jm", "ja", "jyg", "jy", "jc", "jc",
  "jdz", "jm", "jz", "jh", "jn", "jz", "jz", "jj", "jq", "jx",
  "kf", "ksd", "klmy", "kzl", "lb", "lw", "lf", "ls", "ls", "ls",
  "lyg", "lc", "ly", "ly", "lj", "lc", "lf", "lx", "ly", "lz",
  "ls", "la", "lps", "ln", "ly", "ld", "ll", "mas", "mm", "ms",
  "mz", "my", "mdj", "nc", "np", "ny", "nq", "nj", "nd", "nj",
  "pj", "pzh", "pds", "pl", "px", "pe", "pt", "qd", "qn", "qxn",
  "qy", "qy", "qhd", "qz", "qqhe", "qth", "qj", "rkz", "rz", "smx",
  "sm", "sy", "sl", "sq", "sr", "sn", "st", "sw", "sg", "sx",
  "sy", "sy", "szs", "sys", "sz", "sp", "sy", "sh", "sn", "sz",
  "sq", "sz", "tcd", "ta", "ty", "tz", "ts", "tl", "tc", "th",
  "tl", "tl", "tr", "tlf", "wn", "ws", "wz", "wh", "wh", "wlcb",
  "wlmq", "ww", "wz", "wz", "xf", "xt", "xx", "xn", "xy", "xg",
  "xlglm", "xam", "xt", "xn", "xx", "xy", "xy", "xz", "xsbn", "xc",
  "ya", "ya", "yb", "yc", "yj", "yq", "yb", "yc", "yc", "yc",
  "ylhsk", "yc", "yk", "yt", "yy", "yz", "yy", "yl", "yl", "yc",
  "yf", "ys", "yx", "zz", "zjj", "zjk", "zy", "zj", "zq", "zt",
  "zj", "zw", "zk", "zs", "zmd", "zz", "zb", "zg", "zy", "zy",
  "ac", "af", "aj", "an", "aq", "ax", "ay", "ay", "by", "by",
  "bh", "bx", "by", "ba", "bl", "bx", "cn", "cs", "cx", "cd",
  "cf", "ch", "cl", "cl", "cs", "cs", "ct", "ct", "cx", "cy",
  "ca", "cg", "ck", "cw", "cr", "cy", "cz", "ca", "cx", "ch",
  "df", "dt", "dx", "dy", "dp", "dt", "dy", "dy", "dz", "da",
  "dh", "dh", "df", "dq", "dq", "dx", "db", "dj", "dn", "dt",
  "dy", "da", "dh", "dm", "dp", "ds", "dt", "dt", "dx", "dy",
  "dy", "dz", "dc", "djy", "ep", "fk", "fc", "fz", "fc", "fd",
  "fx", "fx", "fc", "fd", "fh", "fj", "fk", "fs", "ft", "fx",
  "fx", "fy", "fy", "fg", "fa", "fd", "fl", "fm", "fn", "fn",
  "fq", "fy", "gx", "gy", "ga", "gc", "gl", "gl", "gm", "gq",
  "gt", "gy", "gy", "gy", "gz", "gy", "gc", "gd", "gf", "gn",
  "gr", "gz", "gn", "gx", "gy", "gx", "gt", "gz", "ha", "hf",
  "hm", "hn", "hy", "hy", "hs", "hc", "hf", "hx", "hp", "hs",
  "hx", "hz", "ha", "hj", "hn", "hy", "ht", "hz", "ha", "hc",
  "hd", "hl", "hm", "hk", "hl", "hq", "hs", "hx", "jd", "jd",
  "jj", "jl", "js", "jy", "jy", "jh", "jn", "jy", "ja", "jl",
  "jn", "jz", "js", "jx", "jd", "js", "jx", "jm", "ja", "jgs",
  "jj", "jn", "jh", "jj", "jm", "jn", "jt", "jt", "jx", "jx",
  "jx", "jz", "jz", "js", "jj", "jt", "jx", "jy", "jy", "jr",
  "jy", "kh", "kp", "kx", "ky", "kp", "kl", "ks", "la", "lx",
  "ly", "lz", "lx", "lt", "lx", "la", "lc", "lz", "ll", "lp",
  "lq", "lt", "lc", "lp", "ls", "lh", "lj", "lj", "ln", "lp",
  "ls", "ls", "lz", "lz", "lc", "lj", "la", "ls", "lx", "lh",
  "lq", "lq", "ly", "lc", "lj", "lx", "la", "lc", "lh", "lk",
  "lm", "ln", "lq", "ly", "ln", "lx", "lf", "lh", "lj", "ld",
  "ln", "ly", "lq", "lq", "lx", "lz", "ms", "mx", "mc", "mj",
  "my", "mz", "mg", "mx", "mh", "mq", "ml", "na", "na", "nc",
  "nc", "nf", "nj", "nk", "nl", "nx", "nd", "ng", "nh", "nh",
  "nj", "nx", "ny", "na", "pa", "ps", "px", "pl", "ps", "pz",
  "pz", "pd", "ph", "ph", "pn", "ps", "pt", "py", "py", "py",
  "py", "py", "pc", "pj", "pj", "pld", "pn", "qa", "qs", "qs",
  "qx", "qd", "qh", "qm", "ql", "qt", "qx", "qy", "qy", "qy",
  "qz", "qz", "qy", "qx", "qj", "qn", "qf", "qj", "rp", "rh",
  "ra", "rc", "rc", "rs", "rd", "rg", "ra", "rc", "rj", "rs",
  "ry", "ry", "sj", "sm", "sg", "sh", "sh", "sl", "sl", "sr",
  "sy", "sy", "sz", "sw", "sx", "sx", "sz", "sy", "sc", "sl",
  "ss", "st", "sx", "sz", "sg", "sn", "sx", "sc", "sl", "sc",
  "sl", "sc", "sh", "sx", "sy", "sc", "sc", "sx", "ss", "sy",
  "tc", "th", "th", "th", "tn", "ts", "ts", "tx", "th", "tc",
  "tt", "tc", "tg", "th", "tl", "tl", "tl", "ts", "tx", "tz",
  "wfd", "wa", "wc", "wj", "wn", "wz", "ws", "wc", "wd", "wy",
  "wl", "wx", "wy", "wc", "wc", "wc", "wh", "wh", "wh", "wj",
  "wj", "wl", "wl", "wm", "wn", "wp", "ws", "ww", "wx", "wy",
  "wys", "xj", "xj", "xs", "xs", "xj", "xy", "xx", "xp", "xf",
  "xa", "xc", "xf", "xf", "xg", "xg", "xh", "xn", "xt", "xz",
  "xj", "xj", "xj", "xl", "xm", "xm", "xt", "xx", "xy", "xy",
  "xz", "xn", "xs", "xs", "xw", "xw", "xd", "xw", "xw", "yc",
  "yd", "yg", "ys", "yx", "yx", "yz", "ys", "yc", "yf", "yh",
  "yl", "yl", "yn", "yd", "ys", "yw", "yx", "yy", "yy", "yz",
  "ya", "yc", "yc", "yd", "yd", "yf", "yj", "yj", "yk", "yt",
  "yx", "yx", "yx", "yy", "ys", "yc", "yd", "yx", "yg", "yh",
  "yj", "yn", "ya", "yh", "yx", "yy", "ys", "ys", "yt", "yt",
  "yy", "yz", "zh", "zc", "zjg", "zp", "zp", "zq", "zs", "zh",
  "zx", "zy", "zd", "zh", "zm", "zx", "zn", "zz", "zh", "zc",
];

/** {省份简写} —— 源码 value13，30 条 */
export const PROVINCE_ABBR: string[] = [
  "hb", "tw", "tj", "nx", "bj", "sh", "qh", "nmg", "gx", "sc",
  "gz", "fj", "yn", "gs", "xg", "ah", "sd", "xz", "jl", "js",
  "hn", "cq", "zj", "xj", "ln", "hlj", "am", "sx", "gd", "jx",
];

/** {城市} —— 去重后的城市全拼（原表有 suzhou/taizhou/jian 等同名重复） */
export const CITY_PINYIN: string[] = Array.from(new Set(CITY_PINYIN_RAW));

/** {城市简写} —— 去重后的城市简写 */
export const CITY_ABBR: string[] = Array.from(new Set(CITY_ABBR_RAW));
